import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[cursor]
style = "Beam"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"



